# Date 03-07-2021
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go


x_random = np.linspace(1, 99.999999, 1000)
y_random = np.cos(x_random)

data = [go.Scatter(x=x_random, y=y_random, mode='markers')]

layout = go.Layout(title="This is a Scatter plot Graph Generated by Plotly",
                   xaxis={"title": "This is a X-Axis"},
                   yaxis=dict(title="This is a Y-Axis"),
                   hovermode="closest")

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename="tutorial_2 (Scatter Plots)[Part-7].html")
