# Date 04-07-2021
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

np.random.seed(56)

x = np.linspace(0, 1, 100)
y = np.random.randn(100)

trace_0 = go.Scatter(x=x,
                     y=y,
                     mode='markers',
                     name="Markers",)

trace_1 = go.Scatter(x=x,
                     y=y+5,
                     mode='lines',
                     name="Line Graph",)

trace_2 = go.Scatter(x=x,
                     y=y+10,
                     mode='lines+markers',
                     name="Lines and Markers combination",)

data = [trace_0, trace_1, trace_2]

layout = go.Layout(title="This is a Scatter plot Graph Generated by Plotly",)

fig = go.Figure(data=data, layout=layout)

pyo.plot(fig, filename="tutorial_3 (Line Charts)[Part-3].html")
